'use client';

import { useEffect, useState } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { useAuthStore } from '@/lib/store/authStore';
import Image from 'next/image';
import Link from 'next/link';

declare global {
  interface Window {
    payhere: any;
  }
}

export default function PaymentPage() {
  const router = useRouter();
  const params = useParams();
  const lessonId = params.lessonId as string;
  const { user, isAuthenticated } = useAuthStore();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!isAuthenticated) {
      router.push('/login');
      return;
    }

    // Load PayHere script
    const script = document.createElement('script');
    script.src = 'https://www.payhere.lk/lib/payhere.js';
    script.async = true;
    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    };
  }, [isAuthenticated, router]);

  // Mock lesson data - will come from API
  const lesson = {
    id: lessonId,
    title: 'Operations with Fractions',
    subject: 'Mathematics',
    grade: 6,
    subjectId: 1,
    description: 'Master adding, subtracting, multiplying, and dividing fractions',
    videoCount: 8,
    totalDuration: '3h 40m',
    price: 750,
    teacher: 'Mr. Samantha Perera',
  };

  const handlePayment = () => {
    setLoading(true);

    const payment = {
      sandbox: process.env.NEXT_PUBLIC_PAYHERE_SANDBOX === 'true',
      merchant_id: process.env.NEXT_PUBLIC_PAYHERE_MERCHANT_ID,
      return_url: `${process.env.NEXT_PUBLIC_BASE_URL}/payment/success`,
      cancel_url: `${process.env.NEXT_PUBLIC_BASE_URL}/payment/cancel`,
      notify_url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/payment/notify`,
      order_id: `LESSON_${lessonId}_${Date.now()}`,
      items: lesson.title,
      amount: lesson.price.toFixed(2),
      currency: 'LKR',
      first_name: user?.name?.split(' ')[0] || 'Student',
      last_name: user?.name?.split(' ').slice(1).join(' ') || '',
      email: 'student@example.com',
      phone: user?.phoneNumber || '',
      address: 'Address',
      city: 'Colombo',
      country: 'Sri Lanka',
      hash: '', // Will be generated by backend in production
    };

    window.payhere.onCompleted = function onCompleted(orderId: string) {
      console.log('Payment completed. OrderID:', orderId);
      setLoading(false);
      router.push(`/payment/success?orderId=${orderId}&lessonId=${lessonId}`);
    };

    window.payhere.onDismissed = function onDismissed() {
      console.log('Payment dismissed');
      setLoading(false);
    };

    window.payhere.onError = function onError(error: any) {
      console.log('Error:', error);
      setLoading(false);
      alert('Payment failed. Please try again.');
    };

    window.payhere.startPayment(payment);
  };

  if (!isAuthenticated) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-gray-50 to-zinc-50">
      {/* Accent Border */}
      <div className="h-1 bg-gradient-to-r from-red-500 via-purple-500 to-pink-500"></div>

      {/* Header */}
      <header className="bg-white shadow-lg border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16 sm:h-20">
            <Link href="/dashboard" className="flex items-center">
              <Image
                src="/images/logo-light.png"
                alt="AIM Academy"
                width={130}
                height={52}
                className="object-contain sm:w-[150px]"
              />
            </Link>

            <Link
              href={`/subject/${lesson.subjectId}`}
              className="flex items-center px-3 sm:px-4 py-2 text-sm font-semibold text-gray-700 hover:text-red-600 hover:bg-red-50 rounded-lg transition"
            >
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
              Cancel
            </Link>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        {/* Progress Steps */}
        <div className="mb-10">
          <div className="flex items-center justify-center space-x-4">
            <div className="flex items-center">
              <div className="w-10 h-10 bg-green-500 rounded-full flex items-center justify-center text-white font-bold shadow-lg">
                ✓
              </div>
              <span className="ml-2 text-sm font-semibold text-gray-700">Select Lesson</span>
            </div>
            <div className="w-16 h-1 bg-blue-500"></div>
            <div className="flex items-center">
              <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold shadow-lg">
                2
              </div>
              <span className="ml-2 text-sm font-semibold text-gray-900">Payment</span>
            </div>
            <div className="w-16 h-1 bg-gray-300"></div>
            <div className="flex items-center">
              <div className="w-10 h-10 bg-gray-300 rounded-full flex items-center justify-center text-gray-600 font-bold">
                3
              </div>
              <span className="ml-2 text-sm font-semibold text-gray-500">Confirmation</span>
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {/* Order Summary - Left */}
          <div className="md:col-span-2">
            <div className="bg-white rounded-2xl shadow-xl p-6 sm:p-8 mb-6">
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Order Summary</h2>

              <div className="border-2 border-gray-200 rounded-xl p-6 mb-6">
                <div className="flex items-start space-x-4">
                  <div className="w-20 h-20 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-xl flex items-center justify-center flex-shrink-0">
                    <svg className="w-10 h-10 text-white" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z" />
                    </svg>
                  </div>
                  <div className="flex-1">
                    <span className="text-xs font-bold text-gray-500 uppercase">
                      Grade {lesson.grade} • {lesson.subject}
                    </span>
                    <h3 className="text-xl font-bold text-gray-900 mt-1 mb-2">
                      {lesson.title}
                    </h3>
                    <p className="text-sm text-gray-600 mb-3">
                      {lesson.description}
                    </p>
                    <div className="flex flex-wrap gap-3 text-sm text-gray-600">
                      <span className="flex items-center">
                        <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                          <path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z" />
                        </svg>
                        {lesson.videoCount} Videos
                      </span>
                      <span className="flex items-center">
                        <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clipRule="evenodd" />
                        </svg>
                        {lesson.totalDuration}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* What You Get */}
              <div className="bg-green-50 border border-green-200 rounded-xl p-6 mb-6">
                <h4 className="font-bold text-green-900 mb-3 flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                  </svg>
                  What You Get:
                </h4>
                <ul className="space-y-2 text-sm text-green-800">
                  <li className="flex items-start">
                    <span className="mr-2">✓</span>
                    <span>Access to all {lesson.videoCount} video lessons</span>
                  </li>
                  <li className="flex items-start">
                    <span className="mr-2">✓</span>
                    <span>2 views per video (total {lesson.videoCount * 2} views)</span>
                  </li>
                  <li className="flex items-start">
                    <span className="mr-2">✓</span>
                    <span>Lifetime access to purchased content</span>
                  </li>
                  <li className="flex items-start">
                    <span className="mr-2">✓</span>
                    <span>Learn at your own pace</span>
                  </li>
                  <li className="flex items-start">
                    <span className="mr-2">✓</span>
                    <span>HD quality video lessons</span>
                  </li>
                </ul>
              </div>

              {/* Teacher Info */}
              <div className="flex items-center space-x-3 text-sm text-gray-600">
                <svg className="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10.394 2.08a1 1 0 00-.788 0l-7 3a1 1 0 000 1.84L5.25 8.051a.999.999 0 01.356-.257l4-1.714a1 1 0 11.788 1.838L7.667 9.088l1.94.831a1 1 0 00.787 0l7-3a1 1 0 000-1.838l-7-3zM3.31 9.397L5 10.12v4.102a8.969 8.969 0 00-1.05-.174 1 1 0 01-.89-.89 11.115 11.115 0 01.25-3.762zM9.3 16.573A9.026 9.026 0 007 14.935v-3.957l1.818.78a3 3 0 002.364 0l5.508-2.361a11.026 11.026 0 01.25 3.762 1 1 0 01-.89.89 8.968 8.968 0 00-5.35 2.524 1 1 0 01-1.4 0zM6 18a1 1 0 001-1v-2.065a8.935 8.935 0 00-2-.712V17a1 1 0 001 1z" />
                </svg>
                <span>Taught by <span className="font-semibold text-gray-900">{lesson.teacher}</span></span>
              </div>
            </div>

            {/* Payment Security */}
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-6">
              <div className="flex items-start">
                <svg className="w-6 h-6 text-blue-600 mt-0.5 mr-3 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M2.166 4.999A11.954 11.954 0 0010 1.944 11.954 11.954 0 0017.834 5c.11.65.166 1.32.166 2.001 0 5.225-3.34 9.67-8 11.317C5.34 16.67 2 12.225 2 7c0-.682.057-1.35.166-2.001zm11.541 3.708a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                </svg>
                <div>
                  <h4 className="font-bold text-blue-900 mb-2">Secure Payment</h4>
                  <p className="text-sm text-blue-800 mb-2">
                    Your payment is processed securely by PayHere, Sri Lanka's most trusted payment gateway.
                  </p>
                  <div className="flex items-center space-x-2 text-xs text-blue-700">
                    <span>✓ SSL Encrypted</span>
                    <span>•</span>
                    <span>✓ PCI DSS Compliant</span>
                    <span>•</span>
                    <span>✓ 100% Secure</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Payment Summary - Right */}
          <div className="md:col-span-1">
            <div className="bg-white rounded-2xl shadow-xl p-6 sticky top-24">
              <h3 className="text-lg font-bold text-gray-900 mb-6">Payment Details</h3>

              <div className="space-y-4 mb-6">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-600">Lesson Price</span>
                  <span className="font-semibold text-gray-900">Rs. {lesson.price}</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-600">Platform Fee</span>
                  <span className="font-semibold text-green-600">Free</span>
                </div>
                <div className="border-t-2 border-gray-200 pt-4 flex items-center justify-between">
                  <span className="text-lg font-bold text-gray-900">Total Amount</span>
                  <span className="text-2xl font-black text-blue-600">Rs. {lesson.price}</span>
                </div>
                <p className="text-xs text-gray-500 text-center">LKR (Sri Lankan Rupees)</p>
              </div>

              <button
                onClick={handlePayment}
                disabled={loading}
                className="w-full bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 disabled:from-gray-300 disabled:to-gray-400 text-white font-bold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all disabled:cursor-not-allowed flex items-center justify-center space-x-2"
              >
                {loading ? (
                  <>
                    <svg className="animate-spin h-5 w-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    <span>Processing...</span>
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M4 4a2 2 0 00-2 2v1h16V6a2 2 0 00-2-2H4z" />
                      <path fillRule="evenodd" d="M18 9H2v5a2 2 0 002 2h12a2 2 0 002-2V9zM4 13a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm5-1a1 1 0 100 2h1a1 1 0 100-2H9z" clipRule="evenodd" />
                    </svg>
                    <span>Proceed to Payment</span>
                  </>
                )}
              </button>

              <p className="text-xs text-gray-500 text-center mt-4">
                By clicking "Proceed to Payment", you agree to our Terms of Service and Privacy Policy
              </p>

              {/* Payment Methods */}
              <div className="mt-6 pt-6 border-t border-gray-200">
                <p className="text-xs font-semibold text-gray-600 mb-3 text-center">We Accept:</p>
                <div className="flex flex-wrap justify-center gap-2">
                  <span className="px-3 py-1 bg-gray-100 text-gray-700 text-xs rounded-lg font-semibold">Visa</span>
                  <span className="px-3 py-1 bg-gray-100 text-gray-700 text-xs rounded-lg font-semibold">Mastercard</span>
                  <span className="px-3 py-1 bg-gray-100 text-gray-700 text-xs rounded-lg font-semibold">Amex</span>
                  <span className="px-3 py-1 bg-gray-100 text-gray-700 text-xs rounded-lg font-semibold">eZ Cash</span>
                  <span className="px-3 py-1 bg-gray-100 text-gray-700 text-xs rounded-lg font-semibold">mCash</span>
                  <span className="px-3 py-1 bg-gray-100 text-gray-700 text-xs rounded-lg font-semibold">Bank Transfer</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}